### ISSUE TITLE
Implementing ToPyObject for () to return PyNone?

### ISSUE THREAD

**Issue by quark-zju** [dgrunwald/rust-cpython#117] opened 2017-11-23 03:50 UTC
Is there some consideration to not implement `ToPyObject` for `()`? That will allow functions without return values to be simply defined as `-> PyResult<()>`.

**Comment by dgrunwald** [comment] 2017-11-23 20:29
Duplicate of #106.

**Closed by dgrunwald** 2017-11-23 20:29 UTC
